### ISSUE TITLE
Give some basic examples in wikilens.daily.titleFormat markdown description

### ISSUE THREAD

**Issue by Tyriar** [lostintangent/wikilens#10]
![image](https://user-images.githubusercontent.com/2193314/130463312-07acc834-2fb7-4ec6-8ff1-e45a293929f5.png)

Most people won't need to look this up if you include basics like

```
dd/mm/yyyy
mm/dd/yyyy
yyyy/mm/dd
```

**Comment by lostintangent** [comment]
Great point! Thanks for this feedback 🙏

**Comment by lostintangent** [comment]
This is fixed in `v0.0.5`. I also added a link to the Moment.js docs, for more details on other format strings.

![image](https://user-images.githubusercontent.com/116461/131231537-a26d69c4-6ae0-4225-afa5-edfe93a12bbf.png)
