### ISSUE TITLE
Wikilens breaks markdown link styles

### ISSUE THREAD

**Issue by Tyriar** [lostintangent/wikilens#12]
Ext disabled:

![image](https://user-images.githubusercontent.com/2193314/130958977-ff0d8477-c32e-405c-bd33-8aebf5d40f1d.png)

Ext enabled:

![image](https://user-images.githubusercontent.com/2193314/130959051-7eb23e15-8556-4f51-a9e4-b6e9cd4ddc80.png)

**Comment by lostintangent** [comment]
This has been fixed in `v0.0.4`. Let me know if you run into any issues/questions when using it. Thanks again for the feedback!
