### ISSUE TITLE
Publish on open-vsx?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [lostintangent/wikilens#29]
Hi!
Congratulations of getting ur extension [published]. I just thought to ask that do u have any plans to publish ur extension on open-vsx??
See this for more details: [lostintangent.wikilens]
Thanks!

[published]: https://code.visualstudio.com/updates/v1_62#_web-extensions
[lostintangent.wikilens]: https://open-vsx.org/vscode/item?itemName=lostintangent.wikilens

**Comment by lostintangent** [comment]
Unfortunately, I don't think I have the bandwidth to support/validate alternative distros of VS Code. So I'm going to close this for now, and we can re-asses it in the future if/when there's higher demand for this. Thanks!

**Comment by goyalyashpal** [comment]
just copying over the input from the other issue for records:

> * https://open-vsx.org/
> * https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
> To make the extension available on Web versions of vscode. Thanks.
