### ISSUE TITLE
Start discussion in backlinks peek is confusing

### ISSUE THREAD

**Issue by Tyriar** [lostintangent/wikilens#7]
![image](https://user-images.githubusercontent.com/2193314/130459158-feaf55dc-7c1d-4fc4-8566-6c58ba8184b7.png)

I'm not familiar with the API but maybe we could allow customizing that title to get something like this?

![image](https://user-images.githubusercontent.com/2193314/130459399-d939f0a6-f0ae-4f73-9230-56d07a719a80.png)

**Comment by lostintangent** [comment]
I believe the "Start Discussion" string is coming from the comment API by default, since I'm not setting that 🤔 That said, I just noticed that the comment thread object has a "label" property, so I'll give that a try and see if it controls this 👍

**Comment by lostintangent** [comment]
This has been fixed in `0.0.4`. Thanks for the feedback!
