### ISSUE TITLE
Hover shouldn't use header style

### ISSUE THREAD

**Issue by Tyriar** [lostintangent/wikilens#8]
![image](https://user-images.githubusercontent.com/2193314/130459708-b997aa62-3624-4506-a5bc-b997055e42a3.png)

**Comment by lostintangent** [comment]
In this case, the hover is actually showing the contents of the linked page. So if you had contents in that page, you'd see it there as well (as opposed to simply showing the title). Does that behavior seem useful? I've been using it as a quick way to peek into linked files without needing to open them.

**Comment by Tyriar** [comment]
Oh ok, I guess that is handy 😃
